### ISSUE TITLE
CanvasI is not defined

### ISSUE THREAD

**Issue by jjdestef3** [jean79/yested#120]
Hi,

Using the 0.0.104 build of Yested and Kotlin 1.0.2. I have a graph on one of the pages in my app. I'm getting an error on line 2113 in Yested.js (return (Kotlin.isType(tmp$0 = this.element, CanvasI) ? tmp$0 : Kotlin.throwCCE()).getContext(id);) that stated CanvasI is not defined. Is the the 104 build not compatible with Kotlin 1.0.2?

Thanks

**Comment by jean79** [comment]
This was fixed in 1.0.3.
