### ISSUE TITLE
Removing underscore prefixes from private fields

### ISSUE THREAD

**Issue by bbodi** [jean79/yested#21]
Yested now follows a convention where private fields contains an underscore prefix.

I think it is highly discouraged. Thanks to the modern IDEs (especially IntelliJ), private fields are syntax highlighted differently from parameters, so there is no need to distinguish them with "_".

Moreover, the Kotlin documentation explicitly prohibit this:
```
never create a private property and call it _foo
```
http://kotlinlang.org/docs/reference/coding-conventions.html

**Comment by jean79** [comment]
Hi,
Thanks, didn't know that. Will fix it.
Jan

On 12. 1. 2015, at 8:54, "Balázs Bódi" <notifications@github.com> wrote:

Yested now follows a convention where private fields contains an underscore
prefix.

I think it is highly discouraged. Thanks to the modern IDEs (especially
IntelliJ), private fields are syntax highlighted differently from
parameters, so there is no need to distinguish them with "_".

Moreover, the Kotlin documentation explicitly prohibit this:

never create a private property and call it _foo

http://kotlinlang.org/docs/reference/coding-conventions.html

—
Reply to this email directly or view it on GitHub
<https://github.com/jean79/yested/issues/21>.
