### ISSUE TITLE
Problem with button handler if there is some text after it

### ISSUE THREAD

**Issue by jean79** [jean79/yested#43]
Sample code:
```
div {
  btsButton(label = {+"click me"}) { //this handler is not called if button is clicked}
  +"This line causes that handler doesn't work"
}
```

somehow it is caused by element.innerHTML += this:
```
public fun String.plus(): Unit {
        element.innerHTML += this
//but it works with  //element.addText(this) - but this prevents entering html code inside a string 
}
```

**Comment by bbodi** [comment]
I tried to reproduce, but it works fine for me.
Chrome 39.0.2171.99 m
Kotlin 0.10.195
```kotlin
div {
    btsButton(label = { +"click me" }) { //this handler is not called if button is clicked}
        +"This line causes that handler doesn't work"
    }
}
```

**Comment by bbodi** [comment]
I found out the problem
```kotlin
div {
  btsButton(label = {+"click me"}) { //this handler is not called if button is clicked}
     +"This line causes that handler doesn't work"
   }
```
If you click the button and the event handler is called, it calls 
```kotlin
element.innerHTML += this
```
It causes that the contents of element.innerHTML is erased, then refilled. So all of the children of the DIV is erased, with all of their event handlers, then the content of the DIV is refilled, but without their eventhandlers.

I think we shouldn't manipulate innerHTML directly, except for trivial cases.

**Comment by jean79** [comment]
Good spot!
fixed, hopefully correctly:
https://github.com/jean79/yested/commit/2960905d9d3040bfde1cd0efe2d4cf4734c083f3
