### ISSUE TITLE
Make table scrollable

### ISSUE THREAD

**Issue by jean79** [jean79/yested#68]
Allow user to set max height of a whole table and have a scrollbar for tbody only.

It is possible to have div with scrollbar:
div {
    "style".."overflow-y: scroll; max-height: 300px"
    +grid
}
but this does not make header  fix.

Unfortunately it is not possible to set this value for tbody.
When I encapsulate tbody within such div as above, it causes that columns width of tbody are different than widths of header columns.

Anybody have some idea?
Should we implement some 3rd party grid javascript library?

**Comment by bbodi** [comment]
```
Should we implement some 3rd party grid javascript library?
```
https://github.com/wenzhixin/bootstrap-table
Looks really impressive

**Comment by jean79** [comment]
implemented in smart grid
